from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 273)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 161, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search.setFont(font)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 4, 0, 1, 1)
        self.find_page = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.find_page.setFont(font)
        self.find_page.setObjectName("find_page")
        self.gridLayout.addWidget(self.find_page, 3, 0, 1, 1)
        self.edit_entry = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edit_entry.setFont(font)
        self.edit_entry.setObjectName("edit_entry")
        self.gridLayout.addWidget(self.edit_entry, 2, 0, 1, 1)
        self.add_a_not = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_a_not.setFont(font)
        self.add_a_not.setStyleSheet("")
        self.add_a_not.setObjectName("add_a_not")
        self.gridLayout.addWidget(self.add_a_not, 1, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(160, 235, 620, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.firstName = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.firstName.setFont(font)
        self.firstName.setObjectName("firstName")
        self.horizontalLayout.addWidget(self.firstName)
        self.lastName = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lastName.setFont(font)
        self.lastName.setObjectName("lastName")
        self.horizontalLayout.addWidget(self.lastName)
        self.surName = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.surName.setFont(font)
        self.surName.setObjectName("surName")
        self.horizontalLayout.addWidget(self.surName)
        self.organization = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.organization.setObjectName("organization")
        self.horizontalLayout.addWidget(self.organization)
        self.workPhone = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.workPhone.setObjectName("workPhone")
        self.horizontalLayout.addWidget(self.workPhone)
        self.personalPhone = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.personalPhone.setObjectName("personalPhone")
        self.horizontalLayout.addWidget(self.personalPhone)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(170, 154, 600, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 93, 600, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_1.setGeometry(QtCore.QRect(170, 32, 600, 21))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 215, 600, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.new_line = QtWidgets.QLineEdit(Form)
        self.new_line.setGeometry(QtCore.QRect(170, 113, 600, 21))
        self.new_line.setObjectName("new_line")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 15, 250, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(170, 75, 250, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(170, 138, 250, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(170, 200, 300, 13))
        self.label_4.setObjectName("label_4")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(780, 10, 700, 261))
        self.listWidget.setObjectName("listWidget")



        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Телефонный справочник"))
        self.search.setText(_translate("Form", "поиск записи"))
        self.find_page.setText(_translate("Form", "найти страницу"))
        self.edit_entry.setText(_translate("Form", "редактировать запись"))
        self.add_a_not.setText(_translate("Form", "добавить запись"))
        self.firstName.setText(_translate("Form", "имя"))
        self.lastName.setText(_translate("Form", "фамилия"))
        self.surName.setText(_translate("Form", "отчество"))
        self.organization.setText(_translate("Form", "организация"))
        self.workPhone.setText(_translate("Form", "раб.ютелефон"))
        self.personalPhone.setText(_translate("Form", "личный телефон"))
        self.comboBox.setItemText(0, _translate("Form", "1 страница"))
        self.comboBox.setItemText(1, _translate("Form", "2 страница"))
        self.comboBox.setItemText(2, _translate("Form", "3 страница"))
        self.label.setText(_translate("Form", "Введите данные, через запятую и пробел «, »"))
        self.label_2.setText(_translate("Form", "Введите данные, через запятую «,»"))
        self.label_3.setText(_translate("Form", "Выберете страницу"))
        self.label_4.setText(_translate("Form", "Выберете 1 критерий по которым хотите найти запись"))





